### ISSUE TITLE
no pysdl2 installation found - Mac & Win

### ISSUE THREAD

**Issue by j1m3n3zj** [bitcraze/crazyflie-clients-python#592]
Hello everyone, I am currently on macOS Monterey, and I am trying to launch the cfclient to use the antenna and gamepad, but I am running into this issue. 

`(venv) (base) juanjimenez@Juans-MBP-3 crazyflie-clients-python % cfclient
CRITICAL:cfclient.gui:No pysdl2 installation found,  #exiting!
(venv) (base) juanjimenez@Juans-MBP-3 crazyflie-clients-python % 
`

I am using the PyCharm IDE and also tried it on the terminal. I also tried to install dl2 on the pip install and uninstalled and reinstalled it. 

 #259 - Was referenced 

Any guidance will help! Thank you

**Comment by knmcguire** [comment]
Hi! Did you install it the client from source or the latest release? 

And the python environment venv, does that only contain cfclient related packages or also other ones from other development environments?

**Comment by j1m3n3zj** [comment]
<img width="983" alt="Screen Shot 2022-03-30 at 10 01 00 AM" src="https://user-images.githubusercontent.com/102626436/160852820-4af5d49d-8baf-425e-be20-b7f68468d1ed.png">
<img width="961" alt="Screen Shot 2022-03-30 at 10 01 35 AM" src="https://user-images.githubusercontent.com/102626436/160852950-34d3e70f-1f83-4a1c-a4af-6643f0b46831.png">

The screenshots above are the ways the instructions that I followed for installation. 

I have tried PyCharm and Anaconda. 

As for your second question, it contains packages from other development environments (to the best of my knowledge) both for Anaconda and PyCharm. 

For example, below, I see the cfclient within the Anaconda IDE, but when I search for the dl2 package, it is not coming up, no matter how many times I reinstall it. 

<img width="1904" alt="Screen Shot 2022-03-30 at 10 04 32 AM" src="https://user-images.githubusercontent.com/102626436/160853587-c702b67b-f412-4d91-8069-f3caa7875faf.png">

Thank you for your time! @knmcguire

**Comment by knmcguire** [comment]
So it is not super clear which way you installed the cfclient (source or from release (pip)) but I assume you installed it with 

`pip3 install cfclient` as I see you have the latest release namely 2022.03.

Could you check with `pip3 list` if you have the [right pysdl packages ](https://github.com/bitcraze/crazyflie-clients-python/blob/e49521ceaddeb651d87d012a2ab69ebb64620c05/setup.py#L76) installed?

**Comment by hhamahl** [comment]
I had the same problem and it was solved by installing the pysdl packages above mentioned. `pip3 install pysdl2`
`pip3 install pysdl2-dll`

**Comment by knmcguire** [comment]
I just confirmed that this is also a problem in a fresh pip environment for windows...

So you would need to do:
`pip install pysdl2~=0.9.6 pysdl2-dll==2.0.1`

It is weird that the setup.py doesn't do this but we should have caught this with the release testing 2 weeks ago, so we would need to do another release relatively soon.

**Comment by knmcguire** [comment]
Just an comment on this: with Win11 and python 3.10, installing it from source, this issue does not happen. Same with installing it directly from pip

**Comment by Lixinlong9** [comment]
> I just confirmed that this is also a problem in a fresh pip environment for windows...
> 
> So you would need to do: `pip install pysdl2~=0.9.6 pysdl2-dll==2.0.1`
> 
> It is weird that the setup.py doesn't do this but we should have caught this with the release testing 2 weeks ago, so we would need to do another release relatively soon.

Is it should be:
`pip install pysdl2~=0.9.6 pysdl2-dll==2.0.16`
?

**Comment by knmcguire** [comment]
ah yes seemed to be a typo indeed. You are right.

**Comment by knmcguire** [comment]
The problem with this issue that this line in setup.py is not handled properly, but there is no idea why this happens. The ifstatement should still hold...

https://github.com/bitcraze/crazyflie-clients-python/blob/45ba7e6d43c9427f26157821bba9e27771e18982/setup.py#L78-L79

**Comment by krichardsson** [comment]
I found this https://til.simonwillison.net/python/platform-specific-dependencies post of how to make platform dependent requirements. Maybe this will solve the problem?

**Comment by krichardsson** [comment]
Fixed in #649

**Comment by knmcguire** [comment]
Unfortunately, when testing this on Windows 11, with an python 3.8 installed through the windows store, the problem remains that pysdl2 is not installed on windows. Hence why I'm reopening it.

**Comment by knmcguire** [comment]
nevermind... that was an older version of the cfclient! now it works with the release candidate
